//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Converter.h"

@class NSImage, NSString, NSTask;

__attribute__((visibility("hidden")))
@interface AudibleConverter : NSObject <Converter>
{
    NSTask *ffmpegTask;
    NSImage *_currentTrackArtwork;
}

+ (id)linesArrayFromMultiplelineString:(id)arg1;
+ (void)initialize;
+ (id)sharedMusicConverter;
@property(retain) NSImage *currentTrackArtwork; // @synthesize currentTrackArtwork=_currentTrackArtwork;
- (BOOL)syncRunToolWithPath:(id)arg1 args:(id)arg2 env:(id)arg3 outputHandler:(CDUnknownBlockType)arg4;
- (BOOL)validActiveCode:(char *)arg1 checksum:(char *)arg2;
- (id)calcActiveBytesForFile:(id)arg1;
- (id)generateFFMPEGCommandWithInput:(id)arg1 output:(id)arg2 duration:(double)arg3 profile:(id)arg4;
- (BOOL)convertFile:(id)arg1 output:(id)arg2 metadata:(id)arg3 convertSpeed:(int)arg4 withProfile:(id)arg5 progressHandler:(CDUnknownBlockType)arg6;
- (void)closeMusicApp;
- (BOOL)openMusicApp;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

