//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface ITunesLibrary : NSObject
{
    NSDictionary *_library;
}

+ (id)xmlLibraryPath;
+ (id)iTunesMusicLibraryPath;
+ (id)iTunesDatabaseLocationDirectory;
+ (id)sharedITuensLibrary;
@property(retain, nonatomic) NSDictionary *library; // @synthesize library=_library;
- (void)dealloc;
- (void)reload;

@end

