//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol AudioConverter <NSObject>
- (NSDictionary *)metadata;
- (BOOL)isConvertingTrack;
- (BOOL)isRunning;
- (void)stop;
- (void)startWithFile:(NSString *)arg1;
- (void)setSpeed:(int)arg1;
- (id)initWithDelegate:(id <AudioConverterDelegate>)arg1;
@end

