//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol AudioConverterDelegate <NSObject>
- (BOOL)converterDidStop;
- (BOOL)converterDidChangeState:(BOOL)arg1;
- (BOOL)converterDidProductData:(struct AudioBufferList *)arg1;
- (BOOL)converterDidStart:(struct AudioStreamBasicDescription)arg1;
@end

