//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PlayerInterface.h"

@class NSString;

@interface ITunesPlayerInterface : PlayerInterface
{
    NSString *currentTrackPath;
}

- (id)artworksForCurrentTrack;
- (id)fetchMetadataForCurrentTrack;
- (BOOL)stopPlay;
- (BOOL)startPlayWithPath:(id)arg1;
- (id)playerApplicationBundleIdentifier;
- (id)playerApplicationURL;
- (int)currentTrackType;

@end

