//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PlayerInterface : NSObject
{
}

- (id)getPropertyAsStringForDesc:(unsigned int)arg1 forObject:(struct AEDesc *)arg2;
- (int)getPropertyAsIntegerForDesc:(unsigned int)arg1 forObject:(struct AEDesc *)arg2;
- (struct AEDesc *)getPropertyOfType:(unsigned int)arg1 forObject:(struct AEDesc *)arg2;
- (id)eventParameterStringForProperty:(unsigned int)arg1;
- (id)stringForOSType:(unsigned int)arg1;
- (int)fetchDurationForCurrentTrack;
- (id)fetchMetadataForCurrentTrack;
- (void)updateCurrentTrackType;
- (int)currentTrackType;
- (BOOL)stopPlay;
- (BOOL)startPlayWithPath:(id)arg1;
- (id)playerApplicationBundleIdentifier;
- (id)playerApplicationURL;

@end

