//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MJRecorder, NSData;

@protocol RecorderDelegate <NSObject>
- (void)recorder:(MJRecorder *)arg1 didReceiveData:(NSData *)arg2;
- (void)recorderDidStop:(MJRecorder *)arg1;
- (void)recorderDidStart:(MJRecorder *)arg1;
@end

