//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AudioConverter.h"
#import "RecorderDelegate.h"

@class MJRecorder, NSObject<OS_dispatch_queue>, NSString, PlayerInterface;

@interface RecorderConverter : NSObject <AudioConverter, RecorderDelegate>
{
    id <AudioConverterDelegate> _delegate;
    MJRecorder *mjrecorder;
    NSObject<OS_dispatch_queue> *dataQueue;
    PlayerInterface *playerInterface;
    BOOL isRunning;
    struct AudioStreamBasicDescription srcAsbd;
}

+ (void)initialize;
- (void)recorder:(id)arg1 didReceiveData:(id)arg2;
- (void)recorderDidStop:(id)arg1;
- (void)recorderDidStart:(id)arg1;
- (void)stop;
- (void)startWithFile:(id)arg1;
- (void)setSpeed:(int)arg1;
- (id)metadata;
- (BOOL)isConvertingTrack;
- (BOOL)isRunning;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

