//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AboutWindowController, NSBundle, NSDictionary, RegisterWindowController, SUUpdater;

@interface ProductController : NSObject
{
    AboutWindowController *aboutWindow;
    RegisterWindowController *registerWindow;
    SUUpdater *updater;
    NSDictionary *infoDictionary;
    NSBundle *bundle;
}

+ (void)setEncryptTemplate:(id)arg1;
+ (id)registerUser;
+ (BOOL)isRegister;
- (void)openRegister:(id)arg1;
- (void)openAbout:(id)arg1;
- (void)checkUpdates:(id)arg1;
- (void)openOnlineHelp:(id)arg1;
- (void)openEmailSupport:(id)arg1;
- (void)openOrderURL:(id)arg1;
- (void)openFaqURL:(id)arg1;
- (void)openWebsiteURL:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (id)valueFromBundleInfoWithKey:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)dealloc;
- (id)init;

@end

