//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSTextField;

@interface RegisterWindowController : NSWindowController
{
    NSTextField *descriptionField;
    id userID;
    id userKey;
    id logo;
    id degelate;
}

+ (BOOL)isLicenseCodeValid:(id)arg1 forUser:(id)arg2;
- (void)openOrderURL:(id)arg1;
- (void)alertDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)enterLicenseCode:(id)arg1;
- (void)setDegelate:(id)arg1;
- (id)init;

@end

